# Introduction to Optimal Transport with Python

#### *Rémi Flamary, Nicolas Courty*

## POT installation

+ Install with pip:
```bash
pip install pot
```
+ Install with conda
```bash
conda install -c conda-forge pot
```

## POT Python Optimal Transport Toolbox

#### Import the toolbox

In [1]:
import numpy as np # always need it
import scipy as sp # often use it
import pylab as pl # do the plots

import ot # ot 

#### Getting help

Online  documentation : [http://pot.readthedocs.io](http://pot.readthedocs.io) 

Or inline help:


In [2]:
help(ot.dist)

Help on function dist in module ot.utils:

dist(x1, x2=None, metric='sqeuclidean')
    Compute distance between samples in x1 and x2 using function scipy.spatial.distance.cdist
    
    Parameters
    ----------
    
    x1 : ndarray, shape (n1,d)
        matrix with n1 samples of size d
    x2 : array, shape (n2,d), optional
        matrix with n2 samples of size d (if None then x2=x1)
    metric : str | callable, optional
        Name of the metric to be computed (full list in the doc of scipy),  If a string,
        the distance function can be 'braycurtis', 'canberra', 'chebyshev', 'cityblock',
        'correlation', 'cosine', 'dice', 'euclidean', 'hamming', 'jaccard', 'kulsinski',
        'mahalanobis', 'matching', 'minkowski', 'rogerstanimoto', 'russellrao', 'seuclidean',
        'sokalmichener', 'sokalsneath', 'sqeuclidean', 'wminkowski', 'yule'.
    
    
    Returns
    -------
    
    M : np.array (n1,n2)
        distance matrix computed with given metric



## A simple OT Problem

This is a simple example with obvious solution. The function emd accepts lists and perform automatic conversion to numpy arrays.

In [3]:
# Problem setting
a=[0.5,0.5]
b=[0.5,0.5]
M=[[0.0,1.0],[1.0,0.0]]

\begin{align}\begin{aligned}\gamma = arg\min_\gamma <\gamma,M>_F\\s.t. \gamma 1 = a
     \gamma^T 1= b
     \gamma\geq 0\end{aligned}\end{align}

In [12]:
from IPython.display import IFrame
IFrame('POT Graph.bmp', width=810, height=621)
# picture refer from https://www.youtube.com/watch?v=mITml5ZpqM8

In [4]:
ot.emd(a,b,M)
# emd function auto transfer 'list[]' input to 'np.array' type and solve the problem

array([[0.5, 0. ],
       [0. , 0.5]])

In [5]:
ot.lp.emd(a,b,M)
# This package multiple types of command for one question.

array([[0.5, 0. ],
       [0. , 0.5]])

In [6]:
ot.emd2(a,b,M)

0.0

\begin{align}\begin{aligned}W = \min_\gamma <\gamma,M>_F + reg\cdot\Omega(\gamma)\\s.t. \gamma 1 = a\\     \gamma^T 1= b\\     \gamma\geq 0\end{aligned}\end{align}

\begin{align}\begin{aligned}\Omega(\gamma)=\sum_{i,j} \gamma_{i,j}\log(\gamma_{i,j})\end{aligned}\end{align}

In [7]:
ot.sinkhorn(a,b,M,1)

array([[0.36552929, 0.13447071],
       [0.13447071, 0.36552929]])

In [8]:
ot.sinkhorn2(a,b,M,1)

array([0.26894142])

In [9]:
ot.bregman.sinkhorn_epsilon_scaling(a,b,M,1)

array([[0.36552929, 0.13447071],
       [0.13447071, 0.36552929]])

\begin{align}\begin{aligned}\gamma = arg\min_\gamma <\gamma,M>_F + reg\cdot\Omega_e(\gamma)
+ \eta \Omega_g(\gamma)\\s.t. \gamma 1 = a\\     \gamma^T 1= b\\     \gamma\geq 0\end{aligned}\end{align}

\begin{align}\Omega_e(\gamma)=\sum_{i,j} \gamma_{i,j}\log(\gamma_{i,j})\end{align}

\begin{align}\Omega_g(\gamma)=\sum_{i,c} \|\gamma_{i,\mathcal{I}_c}\|^{1/2}_1\end{align}

Ωg is the group lasso regulaization term ，where Ic are the index of samples from class c in the source domain.

In [10]:
ot.sinkhorn_lpl1_mm?

You can also have your self-defined regular loss function, via `ot.optim` function.

\begin{align}\begin{aligned}\gamma = arg\min_\gamma <\gamma,M>_F + reg1\cdot\Omega(\gamma) + reg2\cdot f(\gamma)\\s.t. \gamma 1 = a\\     \gamma^T 1= b\\     \gamma\geq 0\end{aligned}\end{align}

f is the regularization term, defined as paramenters:

In [11]:
?ot.optim.gcg
?ot.optim.cg